# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f946907a64d7f421e1f285dd56864f33e6708dc311548140b7754cad06aaf79ef5b9c95b6f76d60095452f721528f2b614171606458d39b3a13507c8ce512b1

test:
  secret_key_base: 7b34140d4cb8a4d24aa8e5a1d9e3dfc64f0ea63203d5793308805ea5e5fb108dbbd46381a84b80f151983ed39867fde9ae8d033033e061034326412230d08e73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
